# Generated by Django 6.0.6 on 2026-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ajustes_frontend'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='area_pesquisa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='projeto',
            name='responsavel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
