# Generated by Django 6.0.6 on 2026-08-08 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projeto_area_pesquisa_projeto_responsavel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='metodologia',
        ),
    ]
